//! Phase 9 — on-chain space-budget test (compile-time).
//!
//! Locks the `INIT_SPACE` of every `#[account]` struct to the values documented
//! in `plan/03_account_model.md` §5 so a field addition or reorder is caught
//! here before it silently drifts the rent cost or breaks PDA layout assumptions
//! in client code.
//!
//! Coverage (`plan/08_testing.md` §3.9):
//!   - `Household::INIT_SPACE         == 101`
//!   - `Member::INIT_SPACE            ==  83`
//!   - `PurchaseRequest::INIT_SPACE   == 218`
//!
//! These are pure constant comparisons — no LiteSVM, no `setup_svm`, no
//! `anchor build` prerequisite. The `INIT_SPACE` constant is generated by
//! Anchor's `#[derive(InitSpace)]` at compile time, so this test runs as part
//! of `cargo test --lib` and the per-target integration pass alike.
//!
//! ## Why a dedicated test
//!
//! The `space = 8 + T::INIT_SPACE` constraint appears in every `init` block in
//! `instructions/`. If a field is added to a state struct without bumping the
//! documented budget, every `init` silently allocates the wrong size and rent
//! exemption drifts. This test is the single source of truth that ties the
//! derived constant to the design doc.

#![cfg(not(target_os = "solana"))]

use anchor_lang::Space;
use stocksie::state::{Household, Member, PurchaseRequest};

/// Documented space budget from `plan/03_account_model.md` §5. Any drift must
/// be a deliberate edit that updates both this constant block and the plan
/// table in the same commit.
const HOUSEHOLD_INIT_SPACE: usize = 101;
const MEMBER_INIT_SPACE: usize = 83;
const PURCHASE_REQUEST_INIT_SPACE: usize = 218;

/// 8-byte Anchor discriminator prefix on every `#[account]`. Kept as a named
/// constant so the on-chain-size arithmetic in the assertion messages stays
/// readable.
const ANCHOR_DISCRIMINATOR_LEN: usize = 8;

#[test]
fn test_space_budget() {
    // ----- Household -------------------------------------------------------
    assert_eq!(
        Household::INIT_SPACE,
        HOUSEHOLD_INIT_SPACE,
        "Household::INIT_SPACE drifted from plan/03_account_model.md §5 \
         ({}B expected, {}B actual). Update the plan table or the struct in \
         lockstep. On-chain size = {}B (discriminator {}B + data).",
        HOUSEHOLD_INIT_SPACE,
        Household::INIT_SPACE,
        ANCHOR_DISCRIMINATOR_LEN + Household::INIT_SPACE,
        ANCHOR_DISCRIMINATOR_LEN,
    );

    // ----- Member ----------------------------------------------------------
    assert_eq!(
        Member::INIT_SPACE,
        MEMBER_INIT_SPACE,
        "Member::INIT_SPACE drifted from plan/03_account_model.md §5 \
         ({}B expected, {}B actual). Update the plan table or the struct in \
         lockstep. On-chain size = {}B (discriminator {}B + data).",
        MEMBER_INIT_SPACE,
        Member::INIT_SPACE,
        ANCHOR_DISCRIMINATOR_LEN + Member::INIT_SPACE,
        ANCHOR_DISCRIMINATOR_LEN,
    );

    // ----- PurchaseRequest -------------------------------------------------
    assert_eq!(
        PurchaseRequest::INIT_SPACE,
        PURCHASE_REQUEST_INIT_SPACE,
        "PurchaseRequest::INIT_SPACE drifted from plan/03_account_model.md §5 \
         ({}B expected, {}B actual). Update the plan table or the struct in \
         lockstep. On-chain size = {}B (discriminator {}B + data).",
        PURCHASE_REQUEST_INIT_SPACE,
        PurchaseRequest::INIT_SPACE,
        ANCHOR_DISCRIMINATOR_LEN + PurchaseRequest::INIT_SPACE,
        ANCHOR_DISCRIMINATOR_LEN,
    );
}
