// Typed IDL entry point for the Stocksie program.
//
// The runtime IDL JSON is generated by `anchor build` into
// `target/idl/stocksie.json` and copied into the frontend by
// `scripts/copy-idl.mjs` (to `idl/stocksie.json`, aliased as `@idl/*`).
// The matching TypeScript type (`Stocksie`) is generated into
// `target/types/stocksie.ts` and copied to `src/lib/generated/stocksie.ts`.
//
// Both artifacts must be regenerated whenever the on-chain program changes;
// `pnpm copy-idl` (or any of `dev`/`build`/`typecheck`, which run it first)
// keeps them in sync.

import idlJson from '@idl/stocksie.json';
import type { Stocksie } from './generated/stocksie';

/**
 * The Stocksie program IDL, typed for the `@anchor-lang/core` client.
 *
 * Cast through `unknown` because the JSON import is structurally a plain
 * object literal type (the inferred shape of the `.json` module), while the
 * generated `Stocksie` type is the precise, camelCased IDL definition used by
 * `Program<Stocksie>` to type `.methods.*` and `.account.*`.
 */
export const idl: Stocksie = idlJson as unknown as Stocksie;

/**
 * The on-chain program address, read straight from the IDL so it can never
 * drift from what `anchor build` produced.
 */
export const PROGRAM_ADDRESS: string = (idlJson as { address: string }).address;
